[Feat] Favorit 함수 추가
limdumb/Watching-JEJU pull request #53
Opened 2023-07-13 03:56 UTC by limdumb

# 제목

* 즐겨찾기 기능 구현

## 변경 내용

* 즐겨찾기 기능 생성
* 즐겨찾기 예외처리 진행
  * 즐겨찾기 추가, 삭제, 로그인이 되어있지않을때의 예외처리

2023-07-13 14:45 UTC, OrangeNebula requested changes

2023-07-13 14:45 UTC, OrangeNebula commented on API/addFavorit.ts
> +
P2: 에러 핸들링 할 게 없으면 try-catch 안쓰니만 못함. (에러가 발생해도, 핸들링이 되지 않으니 에러가 먹혀버려서 개발자가 에러 트래킹을 어렵게 함)

2023-07-13 14:45 UTC, OrangeNebula commented on components/StoreDetailView/DetailHomeView.tsx
> +        <TouchableOpacity
P99: 욕심내보면, 이런 버튼들은 일반화(=디자인 시스템) 시켜서 컴포넌트로 만들어놔도 괜찮을 듯

2023-07-13 14:45 UTC, OrangeNebula commented on components/StoreDetailView/DetailHomeView.tsx
> +              Alert.alert("로그인시 이용 가능한 기능입니다.");
P99: 이런 얼럿 팝업도 욕심내보면 컴포넌트화 해볼 수 있을 듯

2023-07-13 14:45 UTC, OrangeNebula commented on pages/StoreDetailView.tsx
> +      if (userId !== null) {
P9: 마이너한거지만, 의도가 로그인 해서 유저 정보가 있는지를 판단하는 거라면, 그 목적에 맞는 훅이나 유틸 함수를 만들어두는 방법도 있을 듯 
```
const [isLogin] = useAuth();

if (isLogin()) {
  // TBD
}
```

2023-07-18 02:54 UTC, limdumb commented on API/addFavorit.ts
> +  try{
...ㅠ

2023-07-18 02:54 UTC, limdumb commented on components/StoreDetailView/DetailHomeView.tsx
> +        <TouchableOpacity
추가스터디 해보겠습니다!

2023-07-18 02:54 UTC, limdumb commented on components/StoreDetailView/DetailHomeView.tsx
> +              Alert.alert("로그인시 이용 가능한 기능입니다.");
나중에 추가적으로 진행해보겠습니다!

2023-07-18 02:55 UTC, merged